version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/payments
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: me@2023
      SPRING_JPA_SHOW-SQL: 'true'
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
    ports:
      - 10000:10000
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: me@2023
      POSTGRES_DB: payments
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgres
volumes:
  db_data:
