server:
  port: 10000

#Database Configuration
spring:
  data:
    web:
      pageable:
        default-page-size: 10
  datasource:
    url: jdbc:mariadb://localhost:3306/payments
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update # or create-drop, create, none
      properties:
        hibernate:
          jdbc:
            batch_size: 50 # set batch size for batch inserts/updates