#Database Configuration
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/payments
    username: root
    password: sudo
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update # or create-drop, create, none
      properties:
        hibernate:
          jdbc:
            batch_size: 50 # set batch size for batch inserts/updates

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: sudoConnect
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 2
          max-interval: 10s
          multiplier: 2