server:
  port:

#Database Configuration
spring:
  application:
    name: Payments-Monitor
  data:
    web:
      pageable:
        default-page-size: 10
  datasource:
    url: jdbc:mariadb://localhost:3306/payments
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update # or create-drop, create, none
      properties:
        hibernate:
          jdbc:
            batch_size: 50 # set batch size for batch inserts/updates

eureka:
  client:
    enabled: false

payments:
  mpesa:
    url-registration: https://api.safaricom.co.ke/mpesa/c2b/v1/registerurl
    authentication-url: https://api.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
    stk-push-url: https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest
    api:
      username:
      password: