
name: CI for Mpesa

on:
  push:
    branches:
      - main
      - staging
      - actions
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -DskipTests clean package

  docker:
    name: Containerization
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:

          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Get branch name
        id: get_branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - if: ${{ github.ref == 'refs/heads/staging' }}
        name: Build and push Docker image for staging
        run: |

          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/mpesa-gateway:staging .
          docker push ${{ vars.DOCKERHUB_USERNAME }}/mpesa-gateway:staging

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and push Docker image for main
        run: |

          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/mpesa-gateway:latest .
          docker push ${{ vars.DOCKERHUB_USERNAME }}/mpesa-gateway:latest    

      - if: ${{ github.ref == 'refs/heads/actions' }}
        name: Build and push Docker image for actions branch
        run: |

          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/mpesa-gateway:dev .
          docker push ${{ vars.DOCKERHUB_USERNAME }}/mpesa-gateway:dev